src/Pinch.SDK.WebSample/Controllers/MerchantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Pinch.SDK.Merchants;
using Pinch.SDK.WebSample.Helpers;
using Pinch.SDK.WebSample.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Pinch.SDK.WebSample.Controllers
{
    public class MerchantsController : BaseController
    {
        public MerchantsController(IOptions<PinchSettings> settings) : base(settings)
        {            
        }

        public async Task<IActionResult> Index()
        {
            var model = new MerchantsVm()
            {
                MyMerchant = await GetApi().Merchant.GetMerchant(),
                ManagedMerchants = await GetApi().Merchant.GetAllManagedMerchants(),
                ImpersonatedMerchantId = ImpersonatedMerchantId
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> NewManaged()
        {
            return View(new ManagedMerchant());
        }

        [HttpPost]
        public async Task<IActionResult> NewManaged(ManagedMerchant model)
        {
            var result = await GetApi().Merchant.CreateManagedMerchant(new ManagedMerchantCreateOptions()
            {
                AccountName = model.AccountName,
                AccountNumber = model.AccountNumber,
                Bsb = model.Bsb,
                CompanyName = model.CompanyName,
                ContactEmail = model.ContactEmail,
                Postcode = model.Postcode,
                StreetAddress = model.StreetAddress,
                Suburb = model.Suburb,
                Abn = model.Abn,
                CompanyEmail = model.CompanyEmail,
                CompanyPhone = model.CompanyPhone,
                ContactFirstName = model.ContactFirstName,
                ContactLastName = model.ContactLastName,
                ContactPhone = model.ContactPhone,
                State = model.State,
                Dob = model.Dob,
                GovernmentNumber = model.GovernmentNumber
            });

            if (!result.Success)
            {
                result.Errors.ForEach(x =>
                {
                    ModelState.AddModelError(x.PropertyName, x.ErrorMessage);
                });

                return View(model);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit()
        {
            var merchant = await GetApi().Merchant.GetMerchant();

            return View(merchant);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Merchant model)
        {
            var result = await GetApi().Merchant.UpdateMerchant(new MerchantUpdateOptions()
            {
                AccountName = model.AccountName,
                AccountNumber = model.AccountNumber,
                Bsb = model.Bsb,
                CompanyName = model.CompanyName,
                ContactEmail = model.ContactEmail,                
                ContactPhone = model.ContactPhone,
                Postcode = model.Postcode,
                StreetAddress = model.StreetAddress,
                Suburb = model.Suburb,
                State = model.State,
                Abn = model.Abn,
                BankStatementLabel = model.BankStatementLabel,
                DebitMessage = model.DebitMessage,      
                CompanyEmail = model.CompanyEmail,
                CompanyPhone = model.CompanyPhone,
                ContactFirstName = model.ContactFirstName,
                ContactLastName = model.ContactLastName,
                Dob = model.Dob,
                GovernmentNumber = model.GovernmentNumber
            });

            if (!result.Success)
            {
                result.Errors.ForEach(x => { ModelState.AddModelError(x.PropertyName, x.ErrorMessage); });

                return View(model);
            }

            return RedirectToAction("Index");
        }

        public IActionResult Impersonate(string merchantId)
        {
            HttpContext.Session.SetObjectAsJson(SessionConstants.IMPERSONATED_MERCHANT_ID, merchantId);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Unimpersonate()
        {
            HttpContext.Session.Remove(SessionConstants.IMPERSONATED_MERCHANT_ID);

            return RedirectToAction(nameof(Index));
        }
    }
}

src/Pinch.SDK.WebSample/Views/Merchants/Edit.cshtml
@model Pinch.SDK.Merchants.Merchant

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Managed Merchant</h4>
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="CompanyName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CompanyEmail" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CompanyEmail" class="form-control" />
                <span asp-validation-for="CompanyEmail" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CompanyPhone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CompanyPhone" class="form-control" />
                <span asp-validation-for="CompanyPhone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AccountName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AccountName" class="form-control" />
                <span asp-validation-for="AccountName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AccountNumber" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AccountNumber" class="form-control" />
                <span asp-validation-for="AccountNumber" class="text-danger"></span>
            </div>
        </div>         
        <div class="form-group">
            <label asp-for="Bsb" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Bsb" class="form-control" />
                <span asp-validation-for="Bsb" class="text-danger"></span>
            </div>
        </div>        
        <div class="form-group">
            <label asp-for="StreetAddress" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="StreetAddress" class="form-control" />
                <span asp-validation-for="StreetAddress" class="text-danger"></span>
            </div>
        </div>        
        <div class="form-group">
            <label asp-for="Suburb" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Suburb" class="form-control" />
                <span asp-validation-for="Suburb" class="text-danger"></span>
            </div>
        </div>        
        <div class="form-group">
            <label asp-for="State" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
        </div>        
        <div class="form-group">
            <label asp-for="Postcode" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Postcode" class="form-control" />
                <span asp-validation-for="Postcode" class="text-danger"></span>
            </div>
        </div>        
        <div class="form-group">
            <label asp-for="BankStatementLabel" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BankStatementLabel" class="form-control" />
                <span asp-validation-for="BankStatementLabel" class="text-danger"></span>
            </div>
        </div>        
        <div class="form-group">
            <label asp-for="DebitMessage" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DebitMessage" class="form-control" />
                <span asp-validation-for="DebitMessage" class="text-danger"></span>
            </div>
        </div>        
        <div class="form-group">
            <label asp-for="Abn" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Abn" class="form-control" />
                <span asp-validation-for="Abn" class="text-danger"></span>
            </div>
        </div>        
        <div class="form-group">
            <label asp-for="ContactFirstName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ContactFirstName" class="form-control" />
                <span asp-validation-for="ContactFirstName" class="text-danger"></span>
            </div>
        </div>   
        <div class="form-group">
            <label asp-for="ContactLastName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ContactLastName" class="form-control" />
                <span asp-validation-for="ContactLastName" class="text-danger"></span>
            </div>
        </div>   
        <div class="form-group">
            <label asp-for="ContactEmail" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ContactEmail" class="form-control" />
                <span asp-validation-for="ContactEmail" class="text-danger"></span>
            </div>
        </div>   
        <div class="form-group">
            <label asp-for="ContactPhone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ContactPhone" class="form-control" />
                <span asp-validation-for="ContactPhone" class="text-danger"></span>
            </div>
        </div>   
        <div class="form-group">
            <label asp-for="Dob" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Dob" class="form-control" />
                <span asp-validation-for="Dob" class="text-danger"></span>
            </div>
        </div>   
        <div class="form-group">
            <label asp-for="GovernmentNumber" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="GovernmentNumber" class="form-control" />
                <span asp-validation-for="GovernmentNumber" class="text-danger"></span>
            </div>
        </div>  

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Pinch.SDK.WebSample/Views/Merchants/Index.cshtml
@using Newtonsoft.Json
@model MerchantsVm

<h2>
    My Merchant
    <a href="@Url.Action("Edit", "Merchants")" class="btn btn-primary pull-right">Edit Merchant</a>
</h2>

<p>
    <pre>@JsonConvert.SerializeObject(Model.MyMerchant, Formatting.Indented)</pre>
</p>

<h2>
    Managed Merchants
    <a href="@Url.Action("NewManaged", "Merchants")" class="btn btn-primary pull-right">New Managed Merchant</a>
</h2>

<table class="table">
    <thead>
    <tr>
        <th>ID</th>
        <th>Company Name</th>
        <th>Contact Email</th>
        <th>Account Name</th>
        <th>BSB</th>
        <th>Account Number</th>
        <th>Street Address</th>
        <th>Suburb</th>
        <th>Postcode</th>
        <th>Keys</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var merchant in Model.ManagedMerchants)
    {
        <tr>
            <td>
                <p>@merchant.Id</p>
                <p>@merchant.TestMerchantId</p>
            </td>
            <td>@merchant.CompanyName</td>
            <td>@merchant.ContactEmail</td>
            <td>@merchant.AccountName</td>
            <td>@merchant.Bsb</td>
            <td>@merchant.AccountNumber</td>
            <td>@merchant.StreetAddress</td>
            <td>@merchant.Suburb</td>
            <td>@merchant.Postcode</td>
            <td>
                
                <p>@merchant.TestSecretKey</p>
                <p>@merchant.LiveSecretKey</p>
                <p>@merchant.TestPublishableKey</p>
                <p>@merchant.LivePublishableKey</p>
            </td>
        </tr>
    }
    @if (!Model.ManagedMerchants.Any())
    {
        <tr>
            <td colspan="9">You have no managed merchants</td>
        </tr>
    }
    </tbody>
</table>

<h3>Impersonate Merchant</h3>
@if (!string.IsNullOrEmpty(Model.ImpersonatedMerchantId))
{
    <p>Impersonated Merchant ID: <strong>@Model.ImpersonatedMerchantId</strong></p>
    <a href="@Url.Action("Unimpersonate", "Merchants")" class="btn btn-primary">Unimpersonate</a>
}
else
{
    <p>Not currently impersonating.</p>
    <form asp-action="Impersonate">
        <input name="merchantId" />
        <button class="btn btn-primary">Impersonate</button>
    </form>
}

src/Pinch.SDK.WebSample/Views/Merchants/NewManaged.cshtml
@model Pinch.SDK.Merchants.ManagedMerchant

@{
    ViewData["Title"] = "New Managed Merchant";
}

<h2>New</h2>

<form asp-action="NewManaged">
    <div class="form-horizontal">
        <h4>Managed Merchant</h4>
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="CompanyName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Abn" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Abn" class="form-control" />
                <span asp-validation-for="Abn" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CompanyEmail" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CompanyEmail" class="form-control" />
                <span asp-validation-for="CompanyEmail" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CompanyPhone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CompanyPhone" class="form-control" />
                <span asp-validation-for="CompanyPhone" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="AccountName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AccountName" class="form-control" />
                <span asp-validation-for="AccountName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Bsb" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Bsb" class="form-control" />
                <span asp-validation-for="Bsb" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AccountNumber" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AccountNumber" class="form-control" />
                <span asp-validation-for="AccountNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="StreetAddress" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="StreetAddress" class="form-control" />
                <span asp-validation-for="StreetAddress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Suburb" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Suburb" class="form-control" />
                <span asp-validation-for="Suburb" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="State" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Postcode" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Postcode" class="form-control" />
                <span asp-validation-for="Postcode" class="text-danger"></span>
            </div>
        </div>
        <hr/>
        <div class="form-group">
            <label asp-for="ContactFirstName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ContactFirstName" class="form-control" />
                <span asp-validation-for="ContactFirstName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ContactLastName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ContactLastName" class="form-control" />
                <span asp-validation-for="ContactLastName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ContactEmail" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ContactEmail" class="form-control" />
                <span asp-validation-for="ContactEmail" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ContactPhone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ContactPhone" class="form-control" />
                <span asp-validation-for="ContactPhone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Dob" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Dob" class="form-control" />
                <span asp-validation-for="Dob" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="GovernmentNumber" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="GovernmentNumber" class="form-control" />
                <span asp-validation-for="GovernmentNumber" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}