src/Pinch.SDK.WebSample/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Pinch.SDK.WebSample.Helpers;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Pinch.SDK.WebSample.Controllers
{
    public class EventsController : BaseController
    {
        public EventsController(IOptions<PinchSettings> settings) : base(settings)
        {
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var model = await GetApi().Event.GetEventsAll();

            return View(model);
        }

        public async Task<IActionResult> Details(string id)
        {
            var model = await GetApi().Event.Get(id);

            return View(model);
        }
    }
}

src/Pinch.SDK.WebSample/Controllers/PayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Pinch.SDK.Payers;
using Pinch.SDK.Sources;
using Pinch.SDK.WebSample.Helpers;
using Pinch.SDK.WebSample.Models;
using Pinch.SDK.WebSample.ViewModels.Payers;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Pinch.SDK.WebSample.Controllers
{
    public class PayersController : BaseController
    {
        private readonly PinchSettings _settings;

        public PayersController(IOptions<PinchSettings> settings) : base(settings)
        {
            _settings = settings.Value;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var payers = await GetApi().Payer.GetPayersAll();

            if (!payers.Success)
            {
                throw new Exception(string.Join(" - ", payers.Errors.Select(x => x.ErrorMessage)));
            }

            return View(payers.Data.ToList());
        }

        public async Task<IActionResult> Details(string id)
        {
            var payer = await GetApi().Payer.Get(id);
            var payments = await GetApi().Payment.GetForPayer(id);

            var model = new PayerDetailsVm()
            {
                Payer = payer.Data,
                Payments = payments
            };

            return View(model);
        }

        public async Task<IActionResult> New()
        {
            return View("Edit", new PayerDetailed());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var payer = await GetApi().Payer.Get(id);

            if (!payer.Success)
            {
                return BadRequest(payer.Errors);
            }

            return View(payer.Data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(PayerDetailed model)
        {
            var result = await GetApi().Payer.Save(new PayerSaveOptions()
            {
                Id = model.Id,
                FirstName = model.FirstName,
                LastName = model.LastName,
                EmailAddress = model.EmailAddress,
                MobileNumber = model.MobileNumber
            });

            if (!result.Success)
            {
                result.Errors.ForEach(x =>
                {
                    ModelState.AddModelError(x.PropertyName, x.ErrorMessage);
                });

                return View(model);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string id)
        {
            await GetApi().Payer.Delete(id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> NewSource(string payerId)
        {
            return View("NewSource", new SourceSaveVm()
            {
                PayerId = payerId
            });
        }

        [HttpPost]
        public async Task<IActionResult> NewSource(SourceSaveVm model)
        {
            if (!string.IsNullOrEmpty(model.BankAccountBsb))
            {
                model.SourceType = "bank-account";
            }
            else if (!string.IsNullOrEmpty(model.CreditCardToken))
            {
                model.SourceType = "credit-card";
            }

            var result = await GetApi().Payer.SaveSource(model.PayerId, new SourceSaveOptions() 
            {            
                SourceType = model.SourceType,
                BankAccountName = model.BankAccountName,
                BankAccountBsb = model.BankAccountBsb,
                BankAccountNumber = model.BankAccountNumber,
                CreditCardToken = model.CreditCardToken
            });

            if (!result.Success)
            {
                result.Errors.ForEach(x =>
                {
                    ModelState.AddModelError(x.PropertyName, x.ErrorMessage);
                });

                return View(model);
            }

            return RedirectToAction("Details", new {id = model.PayerId});
        }
    }
}

src/Pinch.SDK.WebSample/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Pinch.SDK.Payers;
using Pinch.SDK.Payments;
using Pinch.SDK.WebSample.Helpers;
using Pinch.SDK.WebSample.ViewModels.Payers;
using Pinch.SDK.WebSample.ViewModels.Payments;
using Pinch.SDK.WebSample.ViewModels.Realtime;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Pinch.SDK.WebSample.Controllers
{
    public class PaymentsController : BaseController
    {
        private readonly PinchSettings _settings;

        public PaymentsController(IOptions<PinchSettings> settings) : base(settings)
        {
            _settings = settings.Value;
        }

        public async Task<IActionResult> Scheduled()
        {
            var result = await GetApi().Payment.GetScheduled();
            var payments = result.Data;

            return View(payments.ToList());
        }

        public async Task<IActionResult> Processed()
        {
            var result = await GetApi().Payment.GetProcessed();
            var payments = result.Data;

            return View(payments.ToList());
        }

        [HttpGet]
        public async Task<IActionResult> Realtime()
        {
            var model = new CreateRealtimePaymentVm();

            model.PublishableKey = _settings.PublishableKey;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Realtime(CreateRealtimePaymentVm model)
        {
            var result = await GetApi().Payment.ExecuteRealtime(new RealtimePaymentSaveOptions()
            {
                FullName = model.PayerName,
                Email = model.PayerEmail,
                CreditCardToken = model.CreditCardToken,
                Amount = Convert.ToInt32(model.Amount * 100),                
                Description = model.Description                
            });

            if (!result.Success)
            {
                result.Errors.ForEach(x =>
                {
                    ModelState.AddModelError(x.PropertyName, x.ErrorMessage);
                });

                model.PublishableKey = _settings.PublishableKey;
                return View(model);
            }

            return RedirectToAction("Processed");
        }

        public async Task<IActionResult> Details(string id)
        {
            var payment = await GetApi().Payment.Get(id);

            return View(payment);
        }

        public async Task<IActionResult> New(string payerId)
        {
            return View("Edit", new EditPaymentVm()
            {
                PayerId = payerId
            });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var details = await GetApi().Payment.Get(id);

            var payment = new EditPaymentVm()
            {
                Id = details.Id,
                Amount = details.Amount,
                TransactionDate = details.TransactionDate,
                Description = details.Description,
                PayerId = details.Payer.Id,
                SourceId = details.Attempts.OrderByDescending(x => x.TransactionDate)
                    .FirstOrDefault()?.Source?.Id
            };

            return View(payment);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditPaymentVm model)
        {
            var result = await GetApi().Payment.Save(new PaymentSaveOptions()
            {
                Id = model.Id,
                PayerId = model.PayerId,
                TransactionDate = model.TransactionDate,
                Amount = model.Amount,
                Description = model.Description,
                SourceId = model.SourceId
            });

            if (!result.Success)
            {
                result.Errors.ForEach(x =>
                {
                    ModelState.AddModelError(x.PropertyName, x.ErrorMessage);
                });

                return View(model);
            }

            return RedirectToAction("Scheduled");
        }

        public async Task<IActionResult> Delete(string id)
        {
            await GetApi().Payment.Delete(id);

            return RedirectToAction("Scheduled");
        }
    }
}

src/Pinch.SDK.WebSample/Controllers/PlansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Pinch.SDK.Plans;
using Pinch.SDK.WebSample.Helpers;
using Pinch.SDK.WebSample.ViewModels.Plans;

namespace Pinch.SDK.WebSample.Controllers
{
    public class PlansController : BaseController
    {
        public PlansController(IOptions<PinchSettings> settings) : base(settings)
        {
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var result = await GetApi().Plan.GetPlansAll();

            return View(result.Data ?? new List<Plan>());
        }

        [HttpGet]
        public IActionResult Save()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Save(PlanSaveVm model)
        {
            var options = JsonConvert.DeserializeObject<PlanSaveOptions>(model.JsonData ?? "");

            var result = await GetApi().Plan.Save(options);

            if (!result.Success)
            {
                ModelState.Clear(); // Lets me return a changed model below.

                result.Errors.ForEach(x =>
                {
                    ModelState.AddModelError(x.PropertyName ?? "", x.ErrorMessage);
                });

                model.JsonData = JsonConvert.SerializeObject(result.InlineErrors,Formatting.Indented);

                return View(model);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            var plan = await GetApi().Plan.Get(id);
            var payments = await GetApi().Plan.CalculatedPayments(id, DateTime.UtcNow, 100000);

            var model = new PlanDetailsVm()
            {
                Plan = plan.Data,
                CalculatedPayments = payments.Data
            };

            return View(model);
        }
    }
}

src/Pinch.SDK.WebSample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Pinch.SDK.WebSample</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">Pinch.SDK.WebSample</a>
                </div>
                <div class="navbar-collapse collapse">
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    <li is-active-route asp-controller="Home" asp-action="Index"><a asp-controller="Home" asp-action="Index">Overview</a></li>
                    <li is-active-route asp-controller="Payers"><a asp-controller="Payers" asp-action="Index">Payers</a></li>
                    <li is-active-route asp-controller="Payments" asp-action="Scheduled"><a asp-controller="Payments" asp-action="Scheduled">Scheduled Payments</a></li>
                    <li is-active-route asp-controller="Payments" asp-action="Processed"><a asp-controller="Payments" asp-action="Processed">Processed Payments</a></li>
                    <li is-active-route asp-controller="Payments" asp-action="Realtime"><a asp-controller="Payments" asp-action="Realtime">Realtime Payments</a></li>
                    <li is-active-route asp-controller="Plans" asp-action="Index"><a asp-controller="Plans" asp-action="Index">Plans</a></li>
                    <li is-active-route asp-controller="Transfers"><a asp-controller="Transfers" asp-action="Index">Transfers</a></li>
                    <li is-active-route asp-controller="Events"><a asp-controller="Events" asp-action="Index">Events</a></li>
                    <li is-active-route asp-controller="Merchants"><a asp-controller="Merchants" asp-action="Index">Merchants</a></li>
                    <li is-active-route asp-controller="Home" asp-action="Connect"><a asp-controller="Home" asp-action="Connect">Connect</a></li>
                </ul>
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                @RenderBody()
            </div>
        </div>
        <hr/>
    </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>